export const citadelVault = {
  "Daily Adhkar": [
    { title: "Morning Protection", arabic: "بِسْمِ اللَّهِ الَّذِي لاَ يَضُرُّ مَعَ اسْمِهِ شَىْءٌ فِي الأَرْضِ وَلاَ فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ", transliteration: "Bismillahil-ladhi la yadurru ma'as-mihi shai'un fil-ardi wa la fis-sama'i, wa Huwas-Sami'ul-'Alim", english: "In the Name of Allah with Whose Name there is protection against every kind of harm in the earth or in the heaven, and He is the All-Hearing and All-Knowing.", reference: "Abu Dawud" }
  ],
  "The Rabbana Du'as": [
    { title: "Rabbana 1: For Good in Both Worlds", arabic: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ", transliteration: "Rabbana atina fid-dunya hasanatan wa fil-akhirati hasanatan waqina 'adhaban-nar", english: "Our Lord, give us in this world [that which is] good and in the Hereafter [that which is] good and protect us from the punishment of the Fire.", reference: "Surah Al-Baqarah 2:201", audioPath: "/audio/rabbana-1.mp3" },
    { title: "Rabbana 2: For Patience and Victory", arabic: "رَبَّنَا أَفْرِغْ عَلَيْنَا صَبْرًا وَثَبِّتْ أَقْدَامَنَا وَانصُرْنَا عَلَى الْقَوْمِ الْكَافِرِينَ", transliteration: "Rabbana afrigh 'alayna sabran wa thabbit aqdamana wansurna 'alal-qawmil-kafirin", english: "Our Lord, pour upon us patience and plant firmly our feet and give us victory over the disbelieving people.", reference: "Surah Al-Baqarah 2:250", audioPath: "/audio/rabbana-2.mp3" },
    { title: "Rabbana 3: Do Not Burden Us", arabic: "رَبَّنَا وَلاَ تَحْمِلْ عَلَيْنَا إِصْرًا كَمَا حَمَلْتَهُ عَلَى الَّذِينَ مِن قَبْلِنَا", transliteration: "Rabbana wa la tahmil 'alayna isran kama hamaltahu 'alal-ladhina min qablina", english: "Our Lord, and lay not upon us a burden like that which You laid upon those before us.", reference: "Surah Al-Baqarah 2:286", audioPath: "/audio/rabbana-3.mp3" },
    { title: "Rabbana 4: Do Not Deviate Our Hearts", arabic: "رَبَّنَا لاَ تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِن لَّدُنكَ رَحْمَةً إِنَّكَ أَنتَ الْوَهَّابُ", transliteration: "Rabbana la tuzigh qulubana ba'da idh hadaytana wa hab lana min ladunka rahmatan innaka antal-Wahhab", english: "Our Lord, let not our hearts deviate after You have guided us and grant us from Yourself mercy. Indeed, You are the Bestower.", reference: "Surah Ali 'Imran 3:8", audioPath: "/audio/rabbana-4.mp3" },
    { title: "Rabbana 5: Forgiveness of Sins", arabic: "رَبَّنَا إِنَّنَا آمَنَّا فَاغْفِرْ لَنَا ذُنُوبَنَا وَقِنَا عَذَابَ النَّارِ", transliteration: "Rabbana innana amanna faghfir lana dhunubana waqina 'adhaban-nar", english: "Our Lord, indeed we have believed, so forgive us our sins and protect us from the punishment of the Fire.", reference: "Surah Ali 'Imran 3:16", audioPath: "/audio/rabbana-5.mp3" },
    { title: "Rabbana 6: Seeking Mercy and Forgiveness", arabic: "رَبَّنَا ظَلَمْنَا أَنفُسَنَا وَإِن لَّمْ تَغْفِرْ لَنَا وَتَرْحَمْنَا لَنَكُونَنَّ مِنَ الْخَاسِرِينَ", transliteration: "Rabbana zhalamna anfusana wa in lam taghfir lana wa tarhamna lanakunanna minal-khasirin", english: "Our Lord, we have wronged ourselves, and if You do not forgive us and have mercy upon us, we will surely be among the losers.", reference: "Surah Al-A'raf 7:23", audioPath: "/audio/rabbana-6.mp3" },
    { title: "Rabbana 7: Trust in Allah", arabic: "رَّبَّنَا عَلَيْكَ تَوَكَّلْنَا وَإِلَيْكَ أَنَبْنَا وَإِلَيْكَ الْمَصِيرُ", transliteration: "Rabbana 'alayka tawakkalna wa-ilayka anabna wa-ilaykal-masir", english: "Our Lord, upon You we have relied, and to You we have returned, and to You is the destination.", reference: "Surah Al-Mumtahanah 60:4", audioPath: "/audio/rabbana-7.mp3" },
    { title: "Rabbana 8: Perfect Our Light", arabic: "رَبَّنَا أَتْمِمْ لَنَا نُورَنَا وَاغْفِرْ لَنَا إِنَّكَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ", transliteration: "Rabbana atmim lana nurana waghfir lana innaka 'ala kulli shay-in qadir", english: "Our Lord, perfect for us our light and forgive us. Indeed, You are over all things competent.", reference: "Surah At-Tahrim 66:8", audioPath: "/audio/rabbana-8.mp3" }
  ]
};
